apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
  - image: jzenon/client
    context: client
    sync:
      manual:
      - src: src/**/*.js
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: jzenon/comments
    context: comments
    sync:
      manual:
      - src: '*.js'
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: jzenon/event-bus
    context: event-bus
    sync:
      manual:
      - src: '*.js'
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: jzenon/moderation
    context: moderation
    sync:
      manual:
      - src: '*.js'
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: jzenon/posts
    context: posts
    sync:
      manual:
      - src: '*.js'
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: jzenon/query
    context: query
    sync:
      manual:
      - src: '*.js'
        dest: .
    docker:
      dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
  - ./infra/k8s/*
deploy:
  kubectl: {}